### ISSUE TITLE
Additional training checkpoints?

### ISSUE THREAD

**Issue by HyberionBrew** [rr-learning/trifinger-rl-example#1]
Hi, I want to try out some off-policy evaluation methods with the datasets. Are there any additional training checkpoints available, and would it be possible to get access to them?

**Comment by nicoguertler** [comment]
Hi, we have the training checkpoints for the expert Lift and Push policies. We can convert them to TorchScript such that they work with the example package and upload them. What exactly would you need?

**Comment by HyberionBrew** [comment]
Exactly, I would need some training checkpoints for the expert Lift and Push policies along the training process (ideally at least 2-3, if possible those that were used to generate the mixed dataset?). If you could upload these checkpoints, that would be very useful for me! Thanks for the quick reply :)

**Comment by nicoguertler** [comment]
Hi, sorry for the late reply. I uploaded all the training checkpoints for the Push and Lift tasks here: https://keeper.mpdl.mpg.de/f/ce144b079829480eaf0e/?dl=1
You should be able to swap them with the ones included in the repo to run them.
For the expert datasets, the 'trifinger.pt' policies were used. For the mixed datasets the following exclusive episode ranges were used (the number of episodes is part of the filenames):
* Push: [0, 5100]
* Lift: [12000, 14000]

Let me know if this is what you need.

**Comment by HyberionBrew** [comment]
That's exactly what I needed! Thank you very much!
